name: Workflow de Integração Contínua

on:
  pull_request:
    branches: [ "main" ]

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.
    - run: npm install
    - run: npm test
